### ISSUE TITLE
Variable annotations are ignored

### ISSUE THREAD

**Issue by sobolevn** [best-doctor/flake8-annotations-complexity#1]
Here you only check function annotations: https://github.com/best-doctor/flake8-annotations-complexity/blob/master/flake8_annotations_complexity/ast_helpres.py#L17-L20

However, it is still possible to use really complex variable annotations:

```python
some_value: List[Union[List[str], Dict[str, Dict[str, str]]]] = ...
```

**Comment by Melevir** [comment]
Solved in https://github.com/best-doctor/flake8-annotations-complexity/commit/451ef8307e6c70714cc81d3f9ba95926ce21a667

**Comment by sobolevn** [comment]
@Melevir awesome! Can you please release a new version?
