### ISSUE TITLE
0.0.6 release

### ISSUE THREAD

**Issue by hoefling** [best-doctor/flake8-annotations-complexity#16]
Hi, thank you for this awesome plugin! Please consider creatng a new release that contains the changes introduced in the PR #14. Otherwise, the latest release on PyPI (0.0.5) raises on Python 3.9, forcing us to resort to install from source repo.

Привет, ребята! Спасибо за отличный плагин к `flake8`! К сожалению, текущая версия на PyPI (0.0.5) кидает исключение в связке с Python 3.9 - фикс уже есть в основной ветке (PR #14). Прошу выпустить новую версию 0.0.6, содержащую этот фикс - пока приходится устанавливать плагин с мастер-ветки репозитория.

**Comment by hw-dv** [comment]
@michael-k do you have a plan to release 0.0.6 ? Thanks!

**Comment by michael-k** [comment]
@gillmylady I'm not a maintainer.  Sorry

**Comment by hw-dv** [comment]
@Melevir hope you are doing fine! Do we have a plan to release 0.0.6 for python 3.9?

**Comment by HacKanCuBa** [comment]
I came to report the bug but found this, please release new version! :)

BTW thanks for the package

**Comment by hw-dv** [comment]
Hey @Melevir Hope all good at your side! Would you mind to help release 0.0.6 version for Python3.9?

**Comment by HacKanCuBa** [comment]
Well, the new version seems to have been released 3 days ago :) , but PyPi wasn't updated :(
So close!

**Comment by hoefling** [comment]
@Melevir Please upload the `v0.0.6` release to PyPI as it seems you're the only one having access to PyPI uploads.

**Comment by hoefling** [comment]
I guess this shouldn't be harder than issuing
```sh
$ python setup.py sdist bdist_wheel
$ twine upload dist/*
```

**Comment by Melevir** [comment]
Sorry, this up to @sutorei for now.

**Comment by r4rdsn** [comment]
0.0.6 is out on pypi since Jan 11th. this issue can be closed now
