### ISSUE TITLE
Forbid flat, but long annotations

### ISSUE THREAD

**Issue by Melevir** [best-doctor/flake8-annotations-complexity#8]
This is not nested, but also not okey: `Tuple[str, str, str, int, List, Any, str, Dict, int]`.

**Comment by lowitea** [comment]
Hi, @Melevir, I made a PR (https://github.com/best-doctor/flake8-annotations-complexity/pull/14), but it crashes on Python 3.9 :( I installed this version locally, but locally all tests crash on it. I'll try to figure it out, but maybe I have any ideas on what to look at?

**Comment by Melevir** [comment]
Sorry, I have no idea. 
I could try to debug the thing, but not right now, so I would be happy if you try to fix it.

**Comment by lowitea** [comment]
Ok, i'll try :)

**Comment by Melevir** [comment]
@lowitea how are you doing with this one? :)
